"""Compliance-ready report generation (JSON + HTML)."""

from __future__ import annotations

import html
import json
from dataclasses import asdict
from pathlib import Path
from typing import Iterable, List

from .verifier import MemberResult, VerificationResult


_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>Backup Verification Report</title>
<style>
  body {{ font: 14px/1.45 -apple-system, Segoe UI, Helvetica, Arial, sans-serif; margin: 2rem; color: #222; }}
  h1 {{ margin-top: 0; }}
  .ok {{ color: #0a7a3b; font-weight: 600; }}
  .fail {{ color: #b00020; font-weight: 600; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; }}
  th, td {{ border: 1px solid #ddd; padding: 6px 8px; text-align: left; font-size: 13px; }}
  th {{ background: #f3f4f6; }}
  tr.bad {{ background: #fef2f2; }}
  .meta {{ background: #f8fafc; padding: 0.75rem 1rem; border-left: 4px solid #2563eb; margin: 1rem 0; }}
  code {{ background: #f1f5f9; padding: 1px 4px; border-radius: 3px; }}
</style>
</head><body>
<h1>Backup Verification Report</h1>
<div class="meta">
  <div><strong>Archive:</strong> <code>{archive_path}</code></div>
  <div><strong>SHA-256:</strong> <code>{archive_sha256}</code></div>
  <div><strong>Size:</strong> {archive_size} bytes</div>
  <div><strong>Started:</strong> {started_utc}</div>
  <div><strong>Finished:</strong> {finished_utc}</div>
  <div><strong>Restore test:</strong> {restore}</div>
  <div><strong>Overall:</strong> <span class="{verdict_class}">{verdict}</span></div>
</div>

<h2>Summary</h2>
<ul>{summary_items}</ul>

{errors_block}

<h2>Members ({member_count})</h2>
<table>
  <thead><tr><th>#</th><th>Path</th><th>Status</th><th>Size</th><th>SHA-256</th><th>Detail</th></tr></thead>
  <tbody>{rows}</tbody>
</table>

<p style="margin-top:2rem;color:#666;font-size:12px;">
  Generated by backup-integrity-verifier.
</p>
</body></html>
"""


class ReportBuilder:
    """Render a ``VerificationResult`` as a JSON or HTML report."""

    def __init__(self, result: VerificationResult):
        self.result = result

    # ---- JSON ------------------------------------------------------------

    def to_json(self, indent: int = 2) -> str:
        payload = {
            "archive_path": self.result.archive_path,
            "archive_sha256": self.result.archive_sha256,
            "archive_size": self.result.archive_size,
            "started_utc": self.result.started_utc,
            "finished_utc": self.result.finished_utc,
            "ok": self.result.ok,
            "restore_verified": self.result.restore_verified,
            "summary": self.result.summary,
            "errors": self.result.errors,
            "members": [asdict(m) for m in self.result.member_results],
        }
        return json.dumps(payload, indent=indent)

    def write_json(self, path: Path | str) -> None:
        Path(path).write_text(self.to_json(), encoding="utf-8")

    # ---- HTML ------------------------------------------------------------

    def to_html(self) -> str:
        r = self.result
        verdict = "PASS" if r.ok else "FAIL"
        verdict_class = "ok" if r.ok else "fail"
        summary_items = "".join(
            f"<li><strong>{html.escape(k)}</strong>: {v}</li>"
            for k, v in sorted(r.summary.items())
        ) or "<li>No members processed.</li>"

        restore = (
            "Passed" if r.restore_verified else
            ("Failed" if any("restore" in e for e in r.errors) else "Not run")
        )

        errors_block = ""
        if r.errors:
            items = "".join(f"<li>{html.escape(e)}</li>" for e in r.errors)
            errors_block = f"<h2>Errors</h2><ul>{items}</ul>"

        rows = []
        for i, m in enumerate(r.member_results, 1):
            cls = "" if m.status == "ok" else ' class="bad"'
            rows.append(
                f"<tr{cls}>"
                f"<td>{i}</td>"
                f"<td><code>{html.escape(m.path)}</code></td>"
                f"<td>{html.escape(m.status)}</td>"
                f"<td>{m.observed_size}</td>"
                f"<td><code>{html.escape(m.observed_sha256[:16])}</code></td>"
                f"<td>{html.escape(m.detail or '')}</td>"
                f"</tr>"
            )

        return _HTML_TEMPLATE.format(
            archive_path=html.escape(r.archive_path),
            archive_sha256=html.escape(r.archive_sha256),
            archive_size=r.archive_size,
            started_utc=html.escape(r.started_utc),
            finished_utc=html.escape(r.finished_utc),
            restore=restore,
            verdict=verdict,
            verdict_class=verdict_class,
            summary_items=summary_items,
            errors_block=errors_block,
            member_count=len(r.member_results),
            rows="".join(rows) or "<tr><td colspan=6>No members.</td></tr>",
        )

    def write_html(self, path: Path | str) -> None:
        Path(path).write_text(self.to_html(), encoding="utf-8")
